//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaluteASoldier.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAssignment
    {
        public int ID { get; set; }
        public int MessageID { get; set; }
        public int UserID { get; set; }
        public bool Unread { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
